In [1]:
import numpy as np

#### THE BASICS

In [3]:
a = np.array([1,2,3], dtype = 'int16')
print (a)

[1 2 3]


In [4]:
b = np.array ([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print (b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [5]:
# Get Dimensions 
a.ndim

1

In [6]:
# Get Shapes
b.shape

(2, 3)

In [7]:
#Get Type
a.dtype

dtype('int16')

In [8]:
# Get Size
a.itemsize

2

In [9]:
b.itemsize


8

In [10]:
a.itemsize
b.itemsize

8

In [11]:
# Get total size
a.size * a.itemsize

6

In [12]:
a.nbytes

6

In [13]:
a = np.arange(1,25)
b = np.arange(25,51)

print("array a:", a)
print("\narray b:", b)

array a: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]

array b: [25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]


In [14]:
vector = np.arange(5)
print("Vector shape:", vector.shape)

matrix = np.ones([3, 2])
print("Matrix shape:", matrix.shape)

tensor = np.zeros([2, 3, 3])
print("Tensor shape:", tensor.shape)

Vector shape: (5,)
Matrix shape: (3, 2)
Tensor shape: (2, 3, 3)


In [15]:
tensor

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [16]:
arr = np.arange(1, 10)
print(arr, '\n')

# Reshape to 3x3 matrix
arr = arr.reshape(3, 3)
print(arr, '\n')

# Reshape back to the original size
arr = arr.reshape(9)
print(arr)

[1 2 3 4 5 6 7 8 9] 

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[1 2 3 4 5 6 7 8 9]


In [17]:
arr = np.arange(1, 11).reshape(2, -1)
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [18]:
# Covert the list of lists to a NumPy array
import csv

data = []

with open('./Downloads/MER_T07_02A.csv', 'r') as csvfile:
    file_reader = csv.reader(csvfile, delimiter=',')
    for row in file_reader:
        data.append(row)
        
data = np.array(data)

FileNotFoundError: [Errno 2] No such file or directory: './Downloads/MER_T07_02A.csv'

In [19]:
data.shape

AttributeError: 'list' object has no attribute 'shape'

#### ACCESSING/CHANGING SPECIFIC ELEMENTS , ROWS , COLUMNS ETC.

In [20]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print (a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [21]:
#Get Specific element [r,c]
a[1,5]

13

In [22]:
#Get Specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [23]:
# Get a specific column 
a [ :,2]

array([ 3, 10])

In [24]:
# getting ā little more fancy [start index : end index :steps size]
a [ 0,1:-1:2]

array([2, 4, 6])

In [25]:
a [1,5] = 20
print (a)

a[:,2]=[1,2]
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [26]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [27]:
# get specific element (work outside in)
b[0,1,1]

4

In [28]:
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [29]:
# replace
b [:,1,:] = [[9,9],[8,8]]
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

#### INITIALIZING DIFFERENT TYPES OF ARRAYS

In [30]:
# All 0s matrix
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [31]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [32]:
np.ones ((4,2,2) , dtype ='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [33]:
# Any other number
np.full((3,3),99)

array([[99, 99, 99],
       [99, 99, 99],
       [99, 99, 99]])

In [34]:
np.full((3,3),99, dtype = 'float32')

array([[99., 99., 99.],
       [99., 99., 99.],
       [99., 99., 99.]], dtype=float32)

In [35]:
# Any other number (full line)
np.full_like(a.shape,4)

array([4, 4])

In [36]:
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [37]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.23504797, 0.69935751],
       [0.9706609 , 0.78932218],
       [0.09393854, 0.92751129],
       [0.81172138, 0.09101354]])

In [38]:
# random integer values
np.random.randint(7)

5

In [39]:
np.random.randint(1,8,size =(3,3))

array([[2, 7, 5],
       [6, 5, 6],
       [7, 2, 5]])

In [40]:
np.random.randint(-4,8,size =(3,3))

array([[ 3,  0,  2],
       [ 7,  1,  5],
       [-3,  4,  0]])

In [41]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [42]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [43]:
# reapeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis = 0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [44]:
output = np.ones((5,5))
print(output)
z = np.zeros((3,3))
print(z)
z[1,1] = 9
print(z)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [45]:
output[1:4,1:4]=z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [46]:
output = np.ones((5,5))
print(output)
output[2:5,2:5] =z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 0. 0. 0.]
 [1. 1. 0. 9. 0.]
 [1. 1. 0. 0. 0.]]


#### BE CAREFUL WHEN COPYING ARRAYS

In [47]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [48]:
b = a.copy()
print(a)
print(b)

[1 2 3]
[1 2 3]


In [49]:
b[1] = 5
print(a)
print(b)

[1 2 3]
[1 5 3]


#### MATHEMATICS

In [50]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [51]:
a +2

array([3, 4, 5, 6])

In [52]:
a-2

array([-1,  0,  1,  2])

In [53]:
a*2

array([2, 4, 6, 8])

In [55]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [54]:
b = np.array([1,0,1,0])
a +b

array([2, 2, 4, 4])

In [56]:
a**2

array([ 1,  4,  9, 16])

In [57]:
# take then sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [58]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

#### LINEAR ALGEBRA

In [59]:
a = np.ones((2,3))
print(a)
b = np.full((3,2),8)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[8 8]
 [8 8]
 [8 8]]


In [60]:
a = np.ones((2,3))
print(a)
b = np.full((3,2),7)
print(b)
np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[7 7]
 [7 7]
 [7 7]]


array([[21., 21.],
       [21., 21.]])

In [61]:
c = np.identity(4)
np.linalg.det(c)

1.0

#### STATISTICS

In [62]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [63]:
np.min(stats,axis=1)

array([1, 4])

In [64]:
np.max(stats)

6

In [65]:
np.min(stats)

1

In [66]:
np.max(stats,axis=1)

array([3, 6])

In [67]:
np.sum(stats,axis=0)

array([5, 7, 9])

#### RECOGNIZING ARRAYS

In [68]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [69]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)
after = before.reshape((4,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [70]:
# vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array ([5,6,7,8])
np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [71]:
# Horizontal stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack(h1)

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [72]:
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack(h2)

array([0., 0., 0., 0.])